### ISSUE TITLE
Not working in the Ionic View app

### ISSUE THREAD

**Issue by mackelito** [thgreasi/localForage-cordovaSQLiteDriver#3] opened 2015-09-28 18:57 UTC
When running emulate or run it says "cordovaSQLiteDriver" and all look fine..
but in the view app I get "TypeError: undefined is not an object (evaluating 'a_driver')"

Any ideas?

**Comment by thgreasi** [comment] 2015-09-28 19:04
How does you code compare with the [Exaple Ionic project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp) found in README?
Any chance you have added the script references in the wrong order, or missed to define the driver?

**Comment by mackelito** [comment] 2015-09-28 19:13
I just did a copy/paste on you demo code :)
I am however using "angular-localforage" as a wrapper but that should not have any effect on the alert in your demo code..

(https://github.com/ocombe/angular-localForage)

**Comment by mackelito** [comment] 2015-09-28 19:15
Oh.. I did make one change.. the order of drivers are now

```
localforage.WEBSQL,
localforage.INDEXEDDB,
localforage.LOCALSTORAGE
```

**Comment by thgreasi** [comment] 2015-09-28 19:26
Keep in mind that you need to also import the [Cordova-SQLitePlugin](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/package.json#L17-L21) and properly also [add the driver in your `setDriver` call](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/www/index.html#L27-L32). But I guess you already have done that since you get the "cordovaSQLiteDriver' alert message...

**Comment by thgreasi** [comment] 2015-09-28 19:27
Try initially without angular-forage.

**Comment by mackelito** [comment] 2015-09-28 20:01
Removed angular-forage but got the same result..

**Comment by thgreasi** [comment] 2015-09-29 05:16
Hmmmm i might bre missing something.
Can you provide some extra info regarding the initial description of the issue. Especially on the part "but in the view app"?

**Comment by mackelito** [comment] 2015-09-29 05:20
I run "Ionic serve" to develop in the browser.. it works as expected.
Then I test the app by running "Ionic run" or "Ionic emulate" both work just fine..

Then I build and upload the app ("ionic build" and "Ionic upload") to be able to test the app in the "Ionic View" app and there it fails.

**Comment by thgreasi** [comment] 2015-09-29 05:29
Never actually tested it with ionic view... That's strange... If it works
on the browser and on the device itself, then it shouldn't have problems
anywhere.

**Comment by mackelito** [comment] 2015-09-29 05:36
Well it's when running on the device (thru the "Ionic view" app) that the problem occurs.
Ionic run/emulate runs on my mac

**Comment by thgreasi** [comment] 2015-09-29 05:56
I can confirm that it works on my lg g3, with Ionic Run, when I have it
connected on my Ubuntu laptop. I actually have my example ionic app
installed on my device right now to do some performance testing.
Can you try it out? Otherwise it should be an Ionic View specific issue.

**Comment by mackelito** [comment] 2015-09-29 06:02
hmm.. This is my first Ionic project.. when you say "I can confirm that it works on my lg g3, with Ionic Run, when I have it connected on my Ubuntu laptop." I assume that the app is shown on your actual phone?.. When I run "ionic run" it opens up a xcode simulator...

How do I test it on my iPhone?

**Comment by mackelito** [comment] 2015-09-29 06:07
Ah.. never mind.. Found it in the docs..

**Comment by olliebennett** [comment] 2015-10-07 16:06
Not sure whether it'll help, but the [list of officially supported Ionic View plugins](http://docs.ionic.io/docs/view-usage#section-supported-plugins) does include `com.brodysoft.sqlitePlugin`, which does seem to be the one used ([here](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonicApp/blob/master/package.json#L19)) in your sample ionic project, so I would imagine this is expected to work in Ionic View...

**Comment by mackelito** [comment] 2015-10-07 16:59
Interesting! :)

**Comment by mlynch** [comment] 2016-08-16 17:13
Hey, following up on this. We just added a bunch of new plugins to the iOS release and Android will follow shortly. The sqlite one should be in there now!

**Comment by thgreasi** [comment] 2016-12-27 18:16
Can anyone confirm whether this is still an issue with the latest releases of ionic?

**Comment by thgreasi** [comment] 2017-02-18 20:52
Closing this for now. Feel free to reopen in any case.

**Closed as completed by thgreasi** 2017-02-18 20:52 UTC
