### ISSUE TITLE
Localforage.geItem(‘itemName’, true) does not reject the promise 

### ISSUE THREAD

**Issue by gabn88** [thgreasi/localForage-cordovaSQLiteDriver#34] opened 2018-12-21 15:00 UTC
If the itemName does not exist.

**Comment by thgreasi** [comment] 2018-12-21 21:52
For sure this isn't specific to this repo.
I don't think that LF accepts a second argument for `getItem()` except from the optional callback.
LF will return `null` when such an item isn't available in the store by design.
Closing this for now, but feel free to add more context if you think I misunderstood something.

**Closed as completed by thgreasi** 2018-12-21 21:52 UTC

**Comment by gabn88** [comment] 2018-12-21 22:13
Wow, I implemented localForage completely using this package/guide: https://github.com/scotttrinh/angular-localForage
And it was working great, but I now see this is not the official repo. Hmm, I have to rethink what is the best way to go forward then. Thanks!

**Comment by gabn88** [comment] 2018-12-21 22:15
I think I will drop that package completely, as localforage (as global variable) is defined anyways within my controllers and it only increases complexity in the setup and the chance for issues like these.
